server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: authentication-service
eureka:
  client:
    serviceUrl:
      defaultZone: ${REGISTRY_URL}

jwt:
  config:
    expirationTime: 1200000
    secret: 3bJAp`]4|kzB?~8+
