aserver:
  port: ${SERVER_PORT:8080}


spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
              - PATCH
      routes:
        - id: users-service-users
          uri: lb://users-service
          predicates:
            - Path=/users/**
          filters:
            - RewritePath=/users/(?<path>.*), /users/$\{path}
        - id: users-service-departments
          uri: lb://users-service
          predicates:
            - Path=/departments/**
          filters:
            - RewritePath=/departments/(?<path>.*), /departments/$\{path}
        - id: users-service-password
          uri: lb://users-service
          predicates:
            - Path=/password/**
          filters:
            - RewritePath=/password/(?<path>.*), /password/$\{path}
        - id: authentication-service
          uri: lb://authentication-service
          predicates:
            - Path=/auth/**
          filters:
            - RewritePath=/auth/(?<path>.*), /$\{path}
        - id: projects-service
          uri: lb://projects-service
          predicates:
            - Path=/projects/**
          filters:
            - RewritePath=/projects/(?<path>.*), /projects/$\{path}
        - id: projects-service-clients
          uri: lb://projects-service
          predicates:
            - Path=/clients/**
          filters:
            - RewritePath=/clients/(?<path>.*), /clients/$\{path}
        - id: timesheet-service-consultants
          uri: lb://timesheet-service
          predicates:
            - Path=/consultants/**
          filters:
            - RewritePath=/consultants/(?<path>.*), /consultants/$\{path}
        - id: timesheet-service-managers
          uri: lb://timesheet-service
          predicates:
            - Path=/managers/**
          filters:
            - RewritePath=/managers/(?<path>.*), /managers/$\{path}
        - id: timesheet-service-project-exist
          uri: lb://timesheet-service
          predicates:
            - Path=/timeEntry/**
          filters:
            - RewritePath=/timeEntry/(?<path>.*), /timeEntry/$\{path}

eureka:
  client:
    fetch-registry: true
    serviceUrl:
      defaultZone: ${REGISTRY_URL}
