server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: projects-service
  liquibase:
    change-log: classpath:db/changelog.xml
  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driverClassName: com.mysql.cj.jdbc.Driver
    url: ${DATABASE_URL}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: false
    show-sql: true
eureka:
  client:
    serviceUrl:
      defaultZone: ${REGISTRY_URL}
jwt:
  config:
    expirationTime: 3600000
    secret: 3bJAp`]4|kzB?~8+

api-prefix: "http://beontime.be-academy.pl/gateway"

api-project-exist: "http://beontime.be-academy.pl/gateway/timeEntry/projectExist?guid="