server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: users-service
  liquibase:
    change-log: classpath:db/changelog.xml
  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driverClassName: com.mysql.cj.jdbc.Driver
    url: ${DATABASE_URL}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: false
    show-sql: true
  mail:
    #Login: beontime@gmail.com
    #Pass: Qazwsx12#
    host: smtp.gmail.com
    port: 587
    username: beontime.test
    password: Qazwsx12#
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
eureka:
  client:
    serviceUrl:
      defaultZone: ${REGISTRY_URL}

jwt:
  config:
    expirationTime: 3600000
    secret: 3bJAp`]4|kzB?~8+

authentication:
  publicUrls: "/login,/password"

administration:
  email: "beontime.test@gmail.com"

api-prefix: "http://beontime.be-academy.pl/gateway"